//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition to salary, BYN.
        /// </summary>
        public static string AdditionToSalary {
            get {
                return ResourceManager.GetString("AdditionToSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this entry?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective working time fund, days.
        /// </summary>
        public static string EffectiveWorkingTimeFund {
            get {
                return ResourceManager.GetString("EffectiveWorkingTimeFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly base rate, BYN.
        /// </summary>
        public static string HourBaseRate {
            get {
                return ResourceManager.GetString("HourBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hours worked per day.
        /// </summary>
        public static string HoursOfWorkPerDay {
            get {
                return ResourceManager.GetString("HoursOfWorkPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly base rate, BYN.
        /// </summary>
        public static string MonthlyBaseRate {
            get {
                return ResourceManager.GetString("MonthlyBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performer.
        /// </summary>
        public static string Performer {
            get {
                return ResourceManager.GetString("Performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium coefficient.
        /// </summary>
        public static string PremiumCoefficient {
            get {
                return ResourceManager.GetString("PremiumCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary, BYN.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff coefficient.
        /// </summary>
        public static string TariffCoefficient {
            get {
                return ResourceManager.GetString("TariffCoefficient", resourceCulture);
            }
        }
    }
}
